# Generated by Django 2.2.3 on 2019-07-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20190707_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_mlm_staff',
            field=models.BooleanField(default=False),
        ),
    ]
