# Generated by Django 2.2.3 on 2019-07-14 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("main", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="mlmclient",
            name="client_id",
            field=models.CharField(default="1", max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mlmclient",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mlmclient",
            name="is_valid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mlmclient",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
