# Generated by Django 2.2.3 on 2019-07-28 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mlm.apps.main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20190714_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLMConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mlm_name', models.CharField(max_length=100, verbose_name="Nom de l'institution")),
                ('mlm_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lien URL')),
                ('subscription_amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Motant pour inscription')),
                ('upline_commissions', models.DecimalField(decimal_places=2, max_digits=16, verbose_name="Commissions pour l'upline")),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='mlmclient',
            old_name='is_valid',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='mlmclient',
            name='available_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='mlmclient',
            name='subscription_amount',
            field=models.DecimalField(decimal_places=2, default=mlm.apps.main.models.get_subscription_amount_default, max_digits=16),
        ),
        migrations.AlterField(
            model_name='mlmclient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mlm_clients', related_query_name='mlm_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MLMTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debit_credit', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('reference_number', models.PositiveIntegerField()),
                ('reference_line', models.PositiveIntegerField()),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=16)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mlm_transactions', related_query_name='mlm_transaction', to='main.MLMClient')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mlm_initiated_transactions', related_query_name='mlm_initiated_transaction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
