# Generated by Django 2.2.3 on 2019-07-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190728_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmclient',
            name='is_admin',
        ),
    ]
