# Generated by Django 2.2.3 on 2019-07-30 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_remove_mlmclient_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmclient',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mlm_clients_created', related_query_name='mlm_client_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
