# Generated by Django 2.2.3 on 2019-07-31 03:14

from django.db import migrations, models
import mlm.apps.main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_mlmclient_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmtransaction',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mlmtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('S', 'Simple'), ('A', 'Affiliation'), ('P', 'Produits')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='mlmclient',
            name='available_amount',
            field=models.DecimalField(decimal_places=2, default=mlm.apps.main.models.get_subscription_amount_default, max_digits=16),
        ),
    ]
